import os 
import ast
import numpy as np
import pandas as pd

read_path = '/data1/lgbt_tweets/sentiment/vaccine/vaccine.csv'
data = pd.read_csv(read_path, low_memory=False, lineterminator="\n")

moderna = '(MODERNA|Moderna|Modernas|Modera|ModeRNA|Maderna vaccine|Maderna|moderna|maderna|SpikeVax|Spikevax)'
pfizer = '(Pfizer|pfizer|PFIZER|Pfyzer|Pfeizer|Pfizers|Pfiser|PFizer|Pfitzer|pfiser|Pfizers vaccine|Phizer shots|phizer shot|Pfizer jabbed|Pfiezer|Pfiizer|PHIZER|Pfzier|Pfzer|pfeizer|Pzizer|pzifer|Pizer|Pzifer|Pifzer|fizer|Phizener|Phizer|phizer|P-Brand Vaccine|BioNTech|Biontech|BioNtech|biotech|BioNTTech|BNTX vaccine|BNT162b2|BNT162|BionTech|BNTX|biontech|Pz/B Tec vaccine|PFE vaccine|PPE vaccines|PFZ vaccine|PFE.N|PFE|pfe|COMIRNATY|Comirnaty)'
AZ = '(Astra Zeneca|AstraZeneca|Astrazeneca|astrazeneca|astra zeneca|ASTRAZENECA|astra Zeneca|Astra Zenica|AstraZenica|Astra zenica|astra zenica|Astrazenica|astrazenica|astraderna|Astra vaccination|AstraZenna|Astragenica|AztraSeneca|AztraZeneca|Aztrazeneca|AstroZeneca|Astrozeneca|AsatraZeneca|Astra-Zeneca|Astra-Zenica|Astra-Zeneca vaccine|astrozeneca|aztrazeneca|astazenica|Astera Zeneca|GenXZeneca shot|Astra vaccine|Astra jab|AstraZ|Astra Z|AZ Vax|AZ vax|AZ vac|AZ vaxxed|AZ vaccine|AZ vaccines|AZ Vaccine|AZ vaccination|AZ vaccine shot|AZ vaccinated|AZ jab|AZ jabs|AZ Jabs|AZ shot|AZ shots|AZ covid vaccine|AZ Covid jab|AZ Covid vaccine|AZ COVID shot|AZ COVID vax|AZ COVID vaccines|AZ COVID vaccine|AZ covid jab|AZ No jab|AZ-Oxford vaccine|AZ dose|AZ vacc|AZ one|A-Z vaccine|Az vaccine|az vaccine|Astra one|AZN vaccine|AZN COVID vaccine|AZN COVID-19 Vaccine|AZN COVID-19 vaccine|AZN LN vaccine|AZN shot|AZN|AZD1222|AZD1222 vaccine|AZ/Oxford|ChAdOx1 nCoV-19 vaccine|ChAdOx1 nCoV|ChAdOx1|Vaxzevria|COVIDSHIELD|COVISHIELD|COVID shield|CoviShield|Covid Shield|Covidshield|Covishield|Covid shield|covidshield|covishield|covid shield|Oxford Vaccine|Oxford vaccine|Oxford vaccines|Oxford vaccination|OXFORD vaccine|OxfordAZ vaccine|oxford VACCINE|Oxford Coronavirus Vaccine|Oxford Coronavirus vaccine|Oxford coronavirus vaccine|Oxford COVID vaccine|Oxford COVID-19 vaccine|Oxford COVID shot|Oxford Covid-19 vaccine|Oxford University COVID-19 vaccine|Oxford University vaccine|Oxford Covid vaccine|Oxford covid vaccine|OxfordVaccine|oxfordvaccine|Oxford jab|Oxford vax|Oxford-AZ|Oxford/AZ|Oxford AZ)'
JNJ = '(JohnsonAndJohnson|JohnsonandJohnson|Johnsonandjohnson|Johnson and Johnson|Johnson &amp; Johnson|Johnson&amp;Johnson|Johnson Johnson|JohnsonJohnson|JOHNSON &amp; JOHNSON|JOHNSON JOHNSON|Johnson Johnson coronavirus vaccine|Johnson Johnson\'s vaccine|Johnson Johnson vaccines|Johnson Johnson shot|Johnson and johnson|Johnson Johnson Covid-19 vaccine|Johnson Johnson Covid vaccine|Johnson Johnson COVID vaccine|johnson and johnson|johnson and johnson vaccine|johnsonandjohnson|johnson And Johnson|johnson johnson|JOHNSON JOHNSON COVID-19 VACCINE|JOHNSON AND JOHNSON|Johnson for vaccine|Johnson COVID-19 Vaccine|Johnson COVID-19 vaccine|Johnson\'s COVID-19 Vaccine|Johnson\'s Covid-19 vaccine|Johnson\'s one-shot|Janssen COVID-19 Vaccine|Janssen COVID-19 vaccine|JOHNSON COVID-19 VACCINE|Johnson vaccine|Janssen vaccine|Janssen|janssen|JANSSEN|Janssen/J J|JNJ COVID-19 Vaccine|JNJ COVID-19 VACCINE|JNJ COVID-19 vaccine|JNJ Covid vaccine|JNJ Covid-19 vaccine|JNJ Vaccine|JNJ covid vaccine|JNJ shot|JNJ single-dose vaccine|JNJ vaccine|JNJ vaccine shot|JNJ vaccine single shot|JNJ vax|JnJ vaccine|jnj vaccine|J J/Janssen COVID-19 vaccine|J J Covid-19 Vaccine|J J Covid-19 vaccine|J J COVID - 19 VACCINE|J J COVID-19 vaccine|J J COVID vaccine|J J covid vaccine|J J Vax|J J jab|J J vac|J J Vaccine|J J vaccine|J J vaccines|J J VACCINE|J J vaccination|J J vaccinated|J J vaccinations|J J vaxx|J J vaxxed|J J shot|J J shots|J J one shot|J J Covid shot|J J covid shot|J J Covid vaccine|J J\’s vaccine|J J\'s vaccine|J J/Janssen vaccine|JJ vax|J and J shot|J and J|J and J vaccine|J J vax|J/J|j j shot|J J/Janssen|j j vax|j j vaccine|j and j|J&amp;J|JandJ|J &amp; J vaccine|JJ shots|JJ shot|JJ vaccine|J vaccine)'
# mRNA = '(MRNA shot|MRNA shots|MRNA jab|MRNA jabs|MRNA vax|MNRA vaccine|MNRA vaccines|MRNA vaccine|MRNA VACCINES|MRNA VACCINE|MRNA Vaccine|MRNA Vaccine shots|MRNA injection|MRNA COVID-19 vaccine|MRNA Covid-19 vaccine|MRNA covid vaccine|MRNA FDA Covid vax|mRNA vac|mRNA vacs|mRNA vacc|mRNA Vax|mRNA vaxes|mRNA vaxx|mRNA vaxxed|mRNA vaxs|mRNA vaxxes|mRNA vaccine|mRNA vaccines|mRNA Vaccine|mRNA Vaccines|mRNA vaccinated|mRNA vaccinations|mRNA vaccination|mRNA jab|mRNA jabs|mRNA shot|mRNA shots|mRNA injection|mRNA injections|mRNA COVID-19 vaccination|mRNA COVID-19 vaccines|mRNA COVID-19 vaccine|mRNA Covid-19 vaccines|mRNA COVID vaccines|mRNA COVID vaccine|mRNA Covid vaccines|mRNA Covid vaccine|mRNA covid vaccines|mRNA covid vaccine|mRNA coronavirus vaccine|mRNA based vaccines|mRNA\)vaccine|mRNA-1273 vaccine|mRNA-1273|m-RNA vaccine|m-RNA vaccines|mRNA-based vaccine|mRNA-based vaccines|mRNA based vaccine|messenger RNA vaccines|messenger RNA vaccine|mRNA covid vax|mRNA covid shots|mRNA COVID shots|mRNA Covid shots|mRNA type vaccines|mRNA COVID Vaccines|mRNA COVID19 vaccine|mRNA Covid-19 Vaccine|mRNA Covid-19 vaccine|mRNA coronavirus vaccines|mRNA VACCINES|mRNA“vaccine|mRNA\)vaccines|mRNA\'vaccine|mRNA\'vaccines|mNRA vaccine|mNRA vaccines|mrna COVID-19 Vaccine|mrna COVID-19 shots|mrna Covid vaccines|mrna covid vaccine|mrna covid vaccines|mrna Coronavirus vaccine|mrna \(its covid vax\)|mrna Vaccine|mrna vaccine|mrna vaccines|mrna phase 1 Covid vaccine|mrna Plenty of vaccines|mrna vax|mrna jabs|mrna jab|mrna shots|mrna shot|mRna vaccines|mRna vaccine|Mrna covid vax|Mrna vaccines|Mrna vaccine|Mrna COVID Vaccines|rna shot|rna vaccine|rna vaccines|rona vaccines|rona vaccine|rona shot|COVID mRNA vaccines|\"RNA\" vaccine|\(RNA\) Vaccine|\(RNA\) covid vaccine|RNA vaccine|RNA vaccines|RNA Vaccine|RNA vax|mRNA\"vaccine|mRNA\"vaccines)'
# sinovac = '(Sinovac|SinoVac|Sinovec|sinovac|Sino-vac|SINOVAC|Sinovax|sinovax|Sinovac jabs)'
# sinopharm = '(SINOPHARM|Sinopharm|Sinopharma|SinoPharm|sinopharm)'
# sputnikv = '(Sputnik V|SputnikV|Sputnik |Sputnik-V|SPUTNIK V|SPUTNIK|Sputnik v|Sputnik Vaccine|sputnik vaccine|sputnik V|sputnik v|sputnik|sputnikvaccine)'
# novavax = '(Novavax|novavax|Novovax|Novax|novax|NVAX|NOVAVAX|NVX - CoV2373|NovaVax|Nuvaxovid|Covavax|Covovax)'
# covaxin = '(COVAXIN|Covaxin|Covaxine|covaxine|covaxin|Bharat Biotech vaccine|BBV152)'

vaccine_sentiment = []
vaccine_list = [moderna,pfizer,AZ,JNJ]
name_list = ['moderna','pfizer','AZ','JNJ']
for i in range(len(vaccine_list)):
    vaccine = data[data['full_text'].str.contains(vaccine_list[i], na=False, case=False)]
    positive = len(vaccine[vaccine['sentiment']=='Positive'])
    neutral = len(vaccine[vaccine['sentiment']=='Neutral'])
    negative = len(vaccine[vaccine['sentiment']=='Negative'])
    print(len(vaccine), positive, neutral, negative)
    vaccine_sentiment.append([name_list[i],len(vaccine), positive, neutral, negative])
sentiment = pd.DataFrame(vaccine_sentiment, columns=['vaccine','count','positive','neutral','negative'])
sentiment.to_csv('/data1/lgbt_tweets/vaccine/vaccine_sentiment.csv',index=False)
